# CodeRabbit Configuration for GitHub Spec Kit Training Program
# Version: 2.0 - Schema Compliant Configuration

# Language settings
language: en-US

# Early access features
early_access: false

# Review configuration
reviews:
  # High-level summary and additional features
  high_level_summary: true
  poem: true
  review_status: true
  
  # Path filters (using proper schema)
  path_filters:
    - "**/*.md"
    - "**/*.py" 
    - "**/*.sh"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.json"
    - "**/*.txt"
    - "!node_modules/**"
    - "!.git/**"
    - "!**/*.log"
    - "!**/__pycache__/**"
  
  # Path-specific instructions
  path_instructions:
    - path: "**/*.py"
      instructions: |
        MANDATORY: Focus on code quality, security, and best practices.
        - Check for proper error handling and input validation
        - Verify secure coding practices and avoid common vulnerabilities
        - Ensure proper documentation and type hints
        - Validate performance considerations and resource usage
    
    - path: "**/*.md"
      instructions: |
        MANDATORY: Ensure professional documentation standards.
        - Verify proper Markdown formatting and structure
        - Check for clear, actionable instructions
        - Validate cross-platform compatibility guidance
        - Ensure verification-first workflow compliance
    
    - path: "**/*.yaml"
      instructions: |
        MANDATORY: Validate YAML syntax and configuration standards.
        - Check proper indentation and structure
        - Verify configuration completeness and accuracy
        - Validate security settings and access controls
    
    - path: "tests/**"
      instructions: |
        MANDATORY: Comprehensive testing standards.
        - Ensure proper test coverage and edge cases
        - Validate test isolation and repeatability
        - Check for proper assertions and error scenarios
    
    - path: "**/*"
      instructions: |
        This is a GitHub Spec Kit Training Program repository with MANDATORY REVIEW REQUIREMENTS.
        
        CRITICAL FOCUS AREAS:
        1. VERIFICATION-FIRST WORKFLOW: All instructions must include verification steps
        2. CROSS-PLATFORM COMPATIBILITY: Support Ubuntu 24.04 LTS and Windows 11
        3. MINIMAL TECH STACK: Focus on core tools and avoid unnecessary dependencies
        4. PROFESSIONAL STANDARDS: Maintain enterprise-grade documentation quality
        5. SECURITY COMPLIANCE: Follow security best practices throughout
        
        TRAINING ENVIRONMENT REQUIREMENTS:
        - Module 1 focus: Environment setup and baseline configuration
        - Hands-on learning approach with practical exercises
        - Clear troubleshooting guidance and error handling
        - Scalable foundation for advanced modules

# Chat configuration
chat:
  auto_reply: false

# Knowledge base settings
knowledge_base:
  learnings:
    scope: auto
  
  # Opt out of knowledge base features if needed
  opt_out: false

# Branch patterns (using proper regex format)
branch_patterns:
  # Main development branches
  - "^main$"
  - "^master$"
  - "^develop$"
  - "^dev$"
  
  # Feature and fix branches
  - "^feature/.*$"
  - "^fix/.*$"
  - "^hotfix/.*$"
  - "^release/.*$"
  
  # Training environment workflow patterns
  - "^revise-.*$"
  - "^training/.*$"
  - "^chore/.*$"
  - "^docs/.*$"
  
  # Match all branches (if needed)
  - ".*"
